name: rich_text_view
description: A simple yet powerful rich text view that supports mention, hashtag, email, url and see more.
version: 2.0.0
homepage: https://github.com/nelsonweze/rich_text_view

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter


dev_dependencies:

dependency_overrides:
  material_color_utilities: ^0.8.0
  matcher: ^0.12.16+1
  meta: ^1.11.0
  path: ^1.9.0
  web: ^0.4.0

flutter:

